# Generated by Django 3.1.4 on 2023-03-09 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='data',
            new_name='date',
        ),
    ]
